# mkg/domain/services/compliance_manager.py
"""ComplianceManager — regulatory compliance for MKG signal enrichment.

Ensures all signal recommendations carry appropriate disclaimers, data
source disclosures, and regulatory classifications per:
- SEBI (Investment Advisers) Regulations, 2013
- SEBI Research Analyst Regulations, 2014
- General financial advisory best practices

Every signal enrichment output must be wrapped with compliance metadata
before being consumed by the SignalFlow backend.
"""

import logging
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Optional

logger = logging.getLogger(__name__)


class DisclaimerType(Enum):
    """Types of regulatory disclaimers."""

    NOT_FINANCIAL_ADVICE = "not_financial_advice"
    SEBI_DISCLAIMER = "sebi_disclaimer"
    DATA_SOURCE_DISCLOSURE = "data_source_disclosure"
    AI_GENERATED = "ai_generated"
    PAST_PERFORMANCE = "past_performance"
    RISK_WARNING = "risk_warning"


# Standard disclaimer texts
_DISCLAIMERS: dict[DisclaimerType, str] = {
    DisclaimerType.NOT_FINANCIAL_ADVICE: (
        "This analysis is generated by an AI system and does not constitute "
        "financial advice, investment advice, or a recommendation to buy, sell, "
        "or hold any security. Consult a qualified financial advisor before "
        "making investment decisions."
    ),
    DisclaimerType.SEBI_DISCLAIMER: (
        "This information is provided for educational and informational purposes "
        "only and is not intended as investment advice under SEBI (Investment "
        "Advisers) Regulations, 2013. The provider is not a SEBI-registered "
        "Investment Adviser. Users should conduct their own due diligence."
    ),
    DisclaimerType.DATA_SOURCE_DISCLOSURE: (
        "Analysis is based on publicly available news articles, market data, "
        "and AI-generated entity extraction. Data sources are disclosed with "
        "each analysis. No proprietary or insider information is used."
    ),
    DisclaimerType.AI_GENERATED: (
        "This analysis was generated by an AI system using natural language "
        "processing and knowledge graph analysis. AI-generated content may "
        "contain errors or omissions. Verify all information independently."
    ),
    DisclaimerType.PAST_PERFORMANCE: (
        "Past performance of the AI system's predictions does not guarantee "
        "future results. Market conditions change and historical accuracy "
        "metrics may not reflect future performance."
    ),
    DisclaimerType.RISK_WARNING: (
        "Trading in securities, derivatives, and crypto assets involves "
        "substantial risk of loss. You should carefully consider whether "
        "trading is appropriate for you in light of your financial condition."
    ),
}


class ComplianceManager:
    """Manages regulatory compliance for MKG signal enrichment.

    Responsibilities:
    1. Generate disclaimers for signal outputs
    2. Wrap enrichment data with compliance metadata
    3. Classify impact by regulatory risk level
    4. Generate compliance audit reports
    """

    def __init__(self) -> None:
        self._enrichment_log: list[dict[str, Any]] = []

    def get_disclaimer(self, disclaimer_type: DisclaimerType) -> str:
        """Get the text for a specific disclaimer type."""
        return _DISCLAIMERS.get(disclaimer_type, "")

    def get_all_disclaimers(self) -> list[str]:
        """Get all disclaimer texts."""
        return [text for text in _DISCLAIMERS.values()]

    def wrap_enrichment(
        self,
        enrichment: dict[str, Any],
        data_sources: list[dict[str, Any]],
        supply_chain_risk: float = 0.0,
        confidence_adjustment: int = 0,
    ) -> dict[str, Any]:
        """Wrap an enrichment result with compliance metadata.

        This is the mandatory compliance gate — every enrichment MUST
        pass through this before being served to users.

        Args:
            enrichment: The raw enrichment dict from SignalBridge.
            data_sources: List of data source attribution dicts.
            supply_chain_risk: Risk score for classification.
            confidence_adjustment: Confidence adjustment for classification.

        Returns:
            Compliance-wrapped enrichment with disclaimers, sources, timestamp.
        """
        has_material = enrichment.get("has_material_impact", False)
        risk = supply_chain_risk or enrichment.get("supply_chain_risk", 0.0)
        adj = confidence_adjustment or enrichment.get("confidence_adjustment", 0)

        # Always include these disclaimers
        disclaimers = [
            self.get_disclaimer(DisclaimerType.NOT_FINANCIAL_ADVICE),
            self.get_disclaimer(DisclaimerType.AI_GENERATED),
        ]

        # Add risk warning for material impacts
        if has_material:
            disclaimers.append(self.get_disclaimer(DisclaimerType.RISK_WARNING))

        # Add data source disclosure if sources are present
        if data_sources:
            disclaimers.append(self.get_disclaimer(DisclaimerType.DATA_SOURCE_DISCLOSURE))

        classification = self.classify_impact(risk, adj, has_material)

        wrapped = {
            "enrichment": enrichment,
            "disclaimers": disclaimers,
            "data_sources": data_sources,
            "compliance_timestamp": datetime.now(timezone.utc).isoformat(),
            "classification": classification,
        }

        # Log for audit
        self._enrichment_log.append({
            "timestamp": wrapped["compliance_timestamp"],
            "has_material_impact": has_material,
            "risk_level": classification["risk_level"],
            "data_source_count": len(data_sources),
        })

        return wrapped

    def classify_impact(
        self,
        supply_chain_risk: float,
        confidence_adjustment: int,
        has_material_impact: bool,
    ) -> dict[str, Any]:
        """Classify the regulatory risk level of an enrichment.

        Args:
            supply_chain_risk: Overall supply chain risk [0, 1].
            confidence_adjustment: Signed confidence adjustment.
            has_material_impact: Whether MKG found material impact.

        Returns:
            Classification dict with risk_level, requires_disclosure, reason.
        """
        if not has_material_impact:
            return {
                "risk_level": "low",
                "requires_disclosure": False,
                "reason": "No material impact detected by knowledge graph analysis.",
            }

        abs_adj = abs(confidence_adjustment)

        if supply_chain_risk >= 0.7 or abs_adj >= 10:
            return {
                "risk_level": "high",
                "requires_disclosure": True,
                "reason": (
                    f"High supply chain risk ({supply_chain_risk:.0%}) or significant "
                    f"confidence adjustment ({confidence_adjustment:+d}). "
                    "Requires full data source disclosure and risk warning."
                ),
            }

        if supply_chain_risk >= 0.3 or abs_adj >= 5:
            return {
                "risk_level": "medium",
                "requires_disclosure": True,
                "reason": (
                    f"Moderate supply chain risk ({supply_chain_risk:.0%}) with "
                    f"confidence adjustment ({confidence_adjustment:+d}). "
                    "Data source disclosure recommended."
                ),
            }

        return {
            "risk_level": "low",
            "requires_disclosure": False,
            "reason": (
                f"Low supply chain risk ({supply_chain_risk:.0%}). "
                "Standard disclaimers sufficient."
            ),
        }

    def get_compliance_report(self) -> dict[str, Any]:
        """Generate a compliance audit report.

        Returns:
            Report dict with aggregate stats for audit purposes.
        """
        total = len(self._enrichment_log)
        high_risk = sum(
            1 for entry in self._enrichment_log
            if entry["risk_level"] == "high"
        )
        medium_risk = sum(
            1 for entry in self._enrichment_log
            if entry["risk_level"] == "medium"
        )
        material = sum(
            1 for entry in self._enrichment_log
            if entry["has_material_impact"]
        )

        return {
            "total_enrichments_processed": total,
            "high_risk_count": high_risk,
            "medium_risk_count": medium_risk,
            "material_impact_count": material,
            "generated_at": datetime.now(timezone.utc).isoformat(),
        }
