import Link from 'next/link';

export const metadata = {
  title: 'Terms of Service — SignalFlow AI',
};

export default function TermsOfServicePage() {
  return (
    <main className="min-h-screen pb-12">
      <div className="max-w-3xl mx-auto px-4 py-8">
        <h1 className="text-3xl font-display font-bold mb-2">Terms of Service</h1>
        <p className="text-xs text-text-muted mb-8">Last updated: 24 March 2026</p>

        <div className="space-y-8 text-sm text-text-secondary leading-relaxed">
          {/* 1 */}
          <section>
            <h2 className="text-lg font-display font-semibold text-text-primary mb-2">
              1. Acceptance of Terms
            </h2>
            <p>
              By accessing or using SignalFlow AI (&quot;the Platform&quot;), you agree to be
              bound by these Terms of Service. If you do not agree, do not use the Platform.
            </p>
          </section>

          {/* 2 */}
          <section>
            <h2 className="text-lg font-display font-semibold text-text-primary mb-2">
              2. Service Description
            </h2>
            <p>
              SignalFlow AI is an{' '}
              <strong className="text-text-primary">
                AI-powered market analysis tool for educational and informational purposes
              </strong>
              . It processes publicly available market data using standard technical indicators
              (RSI, MACD, SMA, Bollinger Bands, ATR) and AI-driven sentiment analysis, then
              displays the results as market analysis.
            </p>
          </section>

          {/* 3 — PROMINENT */}
          <section className="bg-signal-sell/5 border border-signal-sell/20 rounded-xl p-4">
            <h2 className="text-lg font-display font-semibold text-signal-sell mb-2">
              ⚠ 3. Not Investment Advice
            </h2>
            <p className="mb-2">
              <strong className="text-text-primary">
                SignalFlow AI is NOT registered with the Securities and Exchange Board of India
                (SEBI) as a Research Analyst or Investment Adviser.
              </strong>
            </p>
            <p className="mb-2">
              The Platform does not provide investment advice, personalized financial
              recommendations, or solicitations to buy or sell any security, cryptocurrency, or
              forex instrument. All analysis displayed is generated by automated algorithms and
              AI models.
            </p>
            <p>
              <strong className="text-text-primary">
                You are solely responsible for your own investment decisions.
              </strong>{' '}
              Past performance metrics shown on this Platform do not guarantee future results.
              Trading and investing involve substantial risk of loss.
            </p>
          </section>

          {/* 4 */}
          <section>
            <h2 className="text-lg font-display font-semibold text-text-primary mb-2">
              4. User Responsibilities
            </h2>
            <ul className="list-disc list-inside space-y-1 ml-2">
              <li>You must be at least 18 years of age to use this Platform.</li>
              <li>
                You are responsible for conducting your own research before making any financial
                decisions.
              </li>
              <li>
                You should consult a SEBI-registered investment advisor or qualified financial
                professional before trading.
              </li>
              <li>
                You agree not to use the Platform for any unlawful purpose or in any way that
                violates applicable laws in your jurisdiction.
              </li>
              <li>
                You are responsible for complying with all applicable laws including FEMA
                regulations for forex trading.
              </li>
            </ul>
          </section>

          {/* 5 */}
          <section>
            <h2 className="text-lg font-display font-semibold text-text-primary mb-2">
              5. Account &amp; Data
            </h2>
            <p>
              You may request deletion of your account and all associated data at any time. See
              our{' '}
              <Link href="/privacy" className="text-accent-purple hover:underline">
                Privacy Policy
              </Link>{' '}
              for details on what data we collect, how it is used, and your rights under the
              DPDPA 2023.
            </p>
          </section>

          {/* 6 */}
          <section>
            <h2 className="text-lg font-display font-semibold text-text-primary mb-2">
              6. Intellectual Property
            </h2>
            <p>
              All content on the Platform — including analysis text, interface design, and AI
              reasoning — is the intellectual property of SignalFlow AI. You may not reproduce,
              distribute, or commercially exploit any content without prior written permission.
            </p>
          </section>

          {/* 7 — PROMINENT */}
          <section className="bg-signal-hold/5 border border-signal-hold/20 rounded-xl p-4">
            <h2 className="text-lg font-display font-semibold text-text-primary mb-2">
              7. Limitation of Liability
            </h2>
            <p className="mb-2">
              <strong className="text-text-primary">
                Under no circumstances shall SignalFlow AI, its creators, or affiliates be
                liable for any direct, indirect, incidental, special, or consequential damages
              </strong>{' '}
              arising from your use of the Platform or reliance on any analysis provided,
              including but not limited to trading losses, loss of profits, or loss of data.
            </p>
            <p>
              The Platform is provided on an &quot;as is&quot; and &quot;as available&quot;
              basis. We make no warranties, expressed or implied, regarding the accuracy,
              reliability, or completeness of any analysis.
            </p>
          </section>

          {/* 8 */}
          <section>
            <h2 className="text-lg font-display font-semibold text-text-primary mb-2">
              8. Disclaimer of Warranties
            </h2>
            <p>
              SignalFlow AI does not warrant that: (a) the analysis will be accurate, timely, or
              error-free; (b) the Platform will be uninterrupted or secure; (c) any analysis
              will result in profitable trades. Market data is sourced from third-party
              providers and may be delayed or inaccurate.
            </p>
          </section>

          {/* 9 */}
          <section>
            <h2 className="text-lg font-display font-semibold text-text-primary mb-2">
              9. Governing Law
            </h2>
            <p>
              These Terms shall be governed by and construed in accordance with the laws of
              India. Any disputes arising from these Terms shall be subject to the exclusive
              jurisdiction of the courts in Bengaluru, India.
            </p>
          </section>

          {/* 10 */}
          <section>
            <h2 className="text-lg font-display font-semibold text-text-primary mb-2">
              10. Changes to Terms
            </h2>
            <p>
              We reserve the right to modify these Terms at any time. Continued use of the
              Platform after changes are posted constitutes acceptance of the modified Terms.
              Material changes will be notified via email or Telegram.
            </p>
          </section>

          {/* 11 */}
          <section>
            <h2 className="text-lg font-display font-semibold text-text-primary mb-2">
              11. Contact
            </h2>
            <p>
              For questions about these Terms, contact us at{' '}
              <a
                href="mailto:legal@signalflow.ai"
                className="text-accent-purple hover:underline"
              >
                legal@signalflow.ai
              </a>
              .
            </p>
          </section>

          {/* Back + related */}
          <div className="pt-4 border-t border-border-default flex items-center gap-4 text-xs">
            <Link href="/privacy" className="text-accent-purple hover:underline">
              Privacy Policy
            </Link>
            <Link href="/" className="text-text-muted hover:text-text-primary">
              ← Back to Dashboard
            </Link>
          </div>
        </div>
      </div>
    </main>
  );
}
