"""initial schema

Revision ID: b0396d5bb542
Revises: 
Create Date: 2026-03-20 16:36:13.365273
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b0396d5bb542'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('markets', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('min_confidence', sa.Integer(), nullable=False),
    sa.Column('signal_types', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('quiet_hours', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_chat_id')
    )
    op.create_table('market_data',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('market_type', sa.String(length=10), nullable=False),
    sa.Column('open', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('high', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('low', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('close', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('volume', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_market_data_symbol_time', 'market_data', ['symbol', sa.literal_column('timestamp DESC')], unique=False)
    op.create_table('signal_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('signal_id', sa.UUID(), nullable=False),
    sa.Column('outcome', sa.String(length=20), nullable=True),
    sa.Column('exit_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('return_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_history_outcome', 'signal_history', ['outcome', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('market_type', sa.String(length=10), nullable=False),
    sa.Column('signal_type', sa.String(length=15), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('target_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('stop_loss', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('timeframe', sa.String(length=50), nullable=True),
    sa.Column('ai_reasoning', sa.Text(), nullable=False),
    sa.Column('technical_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sentiment_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_signals_active', 'signals', ['is_active', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_signals_symbol', 'signals', ['symbol', sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_signals_symbol', table_name='signals')
    op.drop_index('idx_signals_active', table_name='signals')
    op.drop_table('signals')
    op.drop_index('idx_history_outcome', table_name='signal_history')
    op.drop_table('signal_history')
    op.drop_index('idx_market_data_symbol_time', table_name='market_data')
    op.drop_table('market_data')
    op.drop_table('alert_configs')
    # ### end Alembic commands ###
